# Generated by Django 2.2.12 on 2020-07-15 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initial_amount', models.CharField(default='0', max_length=100)),
                ('total_amount', models.CharField(default='0', max_length=100)),
                ('total_amount_gained', models.CharField(default='0', max_length=100)),
                ('total_amount_spent', models.CharField(default='0', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
