# Generated by Django 2.2.12 on 2020-07-28 03:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
