# Generated by Django 3.0.5 on 2020-08-06 02:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_monthly_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monthly_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
