# Generated by Django 2.2.12 on 2020-07-28 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('current_monthly_spent', models.CharField(default='0', max_length=100)),
                ('current_monthly_income', models.CharField(default='0', max_length=100)),
                ('monthly_goal', models.CharField(blank=True, default='0', max_length=100)),
                ('monthly_amount', models.CharField(default='0', max_length=100)),
                ('is_expense', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.CharField(max_length=15, null=True, verbose_name='Income/Expense')),
                ('source', models.CharField(max_length=30, verbose_name='Title')),
                ('amount', models.CharField(default='0', max_length=100)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('date_posted', models.DateField(null=True, verbose_name='Transaction Date (mm/dd/yyyy)')),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgeting.Categories')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
